=== skoona/SknServices/config/content_registry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://skoona.net/SknServices/ContentRegistry"
           xmlns="http://skoona.net/SknServices/ContentRegistry" >
           
  <xs:element name="contentRegistry">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resource" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation>
            <xs:documentation><![CDATA[config/content_registry.xml

               * REQUIRED RESOURCE SYNTAX **********************************************
                                  ** Note: :options are now required for TopicOpts values

                <resource secured="true|false" content="true|false" topicValueRegex="">
                    <uri>CONTENT/TOPIC/TOPIC_VALUE</uri>
                    <description></description>
                    <userdata>CONTENT_VALUE</userdata>
                    <permission type="READ">
                        <authorizedRoles>
                            <authorizedRole options="TOPIC_VALUE RequiredCommaSepTopicValues">Services.CONTENT.TOPIC.Access</authorizedRole>
                        </authorizedRoles>
                    </permission>
                </resource>

                UserData Required format/syntax is:
                   returns Array if value|value,...
                   returns Hash  if key:value|key:value|...
                   returns String if no reserve chars present
                   Reserved chars: |:  # vertical-bar and semi-colon


               ============== Content Access Adaptation  ==========]]>
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    
  <xs:element name="authorizedRole">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:string" name="options" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="authorizedRoles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="authorizedRole" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="permission">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="authorizedRoles"/>
      </xs:sequence>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="READ" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="uri">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="\w+/\w+/\w+" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="description" type="xs:string" />
  <xs:element name="userdata" type="xs:string"/>
  
  <xs:element name="resource">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="uri"/>
        <xs:element ref="description"/>
        <xs:element ref="userdata"/>
        <xs:element ref="permission" maxOccurs="4" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute type="xs:boolean" name="secured" use="required"/>
      <xs:attribute type="xs:boolean" name="content" use="required"/>
      <xs:attribute type="xs:string" name="topicValueRegex" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== skoona/SknServices/config/content_registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<contentRegistry xnlns="http://skoona.net/SknServices/ContentRegistry"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                xsi:schemaLocation="http://skoona.net/SknServices/ContentRegistry content_registry.xsd">

<!-- see: config/content_registry.xsd -->

    <!--============================================================================= -->
    <!--================== Content RESOURCE REGISTRY  =============================== -->
    <!--============================================================================= -->
    <!--
      =============================================================================
      A possible Content Access scheme could be:
         <resource secured="true" content="true">
                                       Todo: ContentType/TopicType/AssetType
           <uri>Commission/Branch/PDF</uri>'
           <description>Branch Commission Statements</description>
                                       Todo: keys to the content: ContentValues
           <userdata>string, array, or hash content_value_opts</userdata>'
           <permission type="READ">'   Todo: Only READ is supported
             <authorizedRoles>         Todo: options contain comma-separated list of all agencies: TopicValues
               <authorizedRole options="0034,0037,0040">Branch.Commission.Access</authorizedRole>
             </authorizedRoles>
           </permission>'
         </resource>
      =============================================================================
      ContentProfile      = UserProfile(user_name)
      ContentProfileEntry = UserProfile(#roles, #user_options) ->
                                ContentRegistry(#roles) ->
                                        Select user_options = authorizedRole(options)
      =============================================================================
      -->

    <!--============== Content Profile Adaptation  ========== -->
    <resource secured="true" content="true">
        <uri>Commission/Branch/PDF</uri>
        <description>Branch Commission Statements</description>
        <userdata>*.pdf</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="0034,0037,0040">Services.Branch.Commission.Statement.PDF.Access</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>Commission/Branch/CSV</uri>
        <description>Branch Commission CSV Datafiles</description>
        <userdata>*.csv</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="0034,0037,0040">Services.Branch.Commission.Statement.CSV.Access</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>Experience/Branch/PDF</uri>
        <description>Branch Experience Statements</description>
        <userdata>*.log</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="0034,0037,0040">Services.Branch.Commission.Experience.PDF.Access</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>Commission/Branch/BAD</uri>
        <description>Test where RoleName has no Options</description>
        <userdata>*.pdf</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole>Services.Branch.Commission.Branch.PDF.Access</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>LicensedStates/Branch/Operations</uri>
        <description>Producer Licensed States</description>
        <userdata>"21|9|23|"</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="0034">Services.Branch.Operations.LicensedStates.USA</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>Activity/Partner/0099</uri>
        <description>Partner Relationship Reports</description>
        <userdata>*.pdf</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="0099">Services.Action.Use.FileDownload.Pdf</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>FileDownload/UserGroups/Pdf</uri>
        <description>Permission to Download PDF Files</description>
        <userdata>*.pdf</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="VendorSecondary,VendorPrimary,EmployeeSecondary">Services.Action.Use.FileDownload.Pdf</authorizedRole>
                <authorizedRole options="Developer,EmployeePrimary">Services.Action.Admin.FileDownload.Pdf</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>FileDownload/UserGroups/Datafiles</uri>
        <description>Permission to Download Data Files</description>
        <userdata>*.log</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="VendorSecondary,VendorPrimary,EmployeeSecondary">Services.Action.Use.FileDownload.Datafile</authorizedRole>
                <authorizedRole options="Developer,EmployeePrimary">Services.Action.Admin.FileDownload.Datafile</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

    <resource secured="true" content="true">
        <uri>FileDownload/UserGroups/Images</uri>
        <description>Permission to Download Image Files</description>
        <userdata>*.png|*.jpg</userdata>
        <permission type="READ">
            <authorizedRoles>
                <authorizedRole options="VendorSecondary,VendorPrimary,EmployeeSecondary">Services.Action.Use.FileDownload.Image</authorizedRole>
                <authorizedRole options="Developer,EmployeePrimary">Services.Action.Admin.FileDownload.Image</authorizedRole>
            </authorizedRoles>
        </permission>
    </resource>

</contentRegistry>
